MODULE   = $(shell basename $(CURDIR))
INCLUDES = -I../include -I../drivers/include -I../lib -I../../cpu/$(CPU)/include -I../../cpu/ -I../lib/cmdengine -I../net -I../../hal/include -I../../core/include -I../config -I$(RIOTBASE)

include $(MAKEBASE)/Makefile.base


